version: '3.9'
services:
  web:
    container_name: openmusic_web
    build:
      context: ./
      target: dev
    restart: always
    depends_on:
      - db
    volumes:
      - .:/src
    command: npm run dev
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
  db:
    container_name: openmusic_postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    container_name: openmusic_pgadmin4
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMINEMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGPASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  db:
    driver: local
  pgadmin:
    driver: local
