version: '3.9'
services:
  api:
    container_name: openmusic_api
    build:
      context: ./
      target: dev
    restart: always
    depends_on:
      - db
    volumes:
      - .:/srv/app
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: development
      HOST : ${DOCKER_HOST}
      PORT : ${PORT}
      PGHOST: ${PG_DOCKER_SERVICE_NAME}
      PGPORT: ${PGPORT}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
      PGDATABASE: ${PGDATABASE}
  db:
    container_name: openmusic_postgres
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - ${PGPORT}:${PGPORT}
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${PGDATABASE}", "-U", "${PGUSER}" ]
      timeout: 45s
      interval: 10s
      retries: 10
  pgadmin:
    container_name: openmusic_pgadmin4
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMINEMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGPASSWORD}
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  db:
    driver: local
  pgadmin:
    driver: local
